'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace B2P.PaymentLanding.Express.Web
    
    Partial Public Class confirm
        
        '''<summary>
        '''docHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents docHead As Global.System.Web.UI.HtmlControls.HtmlHead
        
        '''<summary>
        '''lnkCSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkCSS As Global.System.Web.UI.HtmlControls.HtmlLink
        
        '''<summary>
        '''frmDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmDefault As Global.System.Web.UI.HtmlControls.HtmlForm
        
        '''<summary>
        '''phDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phDefault As Global.B2P.PaymentLanding.Express.Web.Header
        
        '''<summary>
        '''pnlNonSSOBreadcrumb control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlNonSSOBreadcrumb As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''pnlSSOBreadcrumb control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSSOBreadcrumb As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''litReviewPayment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litReviewPayment As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litEditDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litEditDetails As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''pnlAccountDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAccountDetails As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''pnlAccount1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAccount1 As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''litAccountNumber1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAccountNumber1 As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litAccountNumber1Data control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAccountNumber1Data As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''pnlAccount2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAccount2 As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''litAccountNumber2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAccountNumber2 As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litAccountNumber2Data control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAccountNumber2Data As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''pnlAccount3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAccount3 As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''litAccountNumber3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAccountNumber3 As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litAccountNumber3Data control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAccountNumber3Data As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''pnlNameonAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlNameonAccount As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''litNameonAccountText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litNameonAccountText As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litNameOnAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litNameOnAccount As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''pnlAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAddress As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''litAddressLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAddressLabel As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAddress As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litPaymentMethodText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPaymentMethodText As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litPaymentMethod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPaymentMethod As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litAmountText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAmountText As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAmount As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''pnlFees control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlFees As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''litFeeText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litFeeText As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litFee control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litFee As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litTotalAmountText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTotalAmountText As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litTotalAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTotalAmount As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''cptConfirmPaymentInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cptConfirmPaymentInfo As Global.B2P.PaymentLanding.Express.Web.TermsConditions
        
        '''<summary>
        '''pnlFeeAgreement control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlFeeAgreement As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''cptConfirmFeeInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cptConfirmFeeInfo As Global.B2P.PaymentLanding.Express.Web.ConvenienceFee
        
        '''<summary>
        '''btnCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnSubmit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnPleaseWait control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnPleaseWait As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''pfDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pfDefault As Global.B2P.PaymentLanding.Express.Web.Footer
        
        '''<summary>
        '''litTermsTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTermsTitle As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''txtTerms control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTerms As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnTermsConfirm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnTermsConfirm As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''litFeesTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litFeesTitle As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''txtFees control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFees As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnFeesConfirm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnFeesConfirm As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''Literal1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Literal1 As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''pnlACHFee control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlACHFee As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''litBankAccountPaymentsTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litBankAccountPaymentsTitle As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litACHFee control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litACHFee As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''pnlCCFee control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCCFee As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''litCreditCardPaymentsTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCreditCardPaymentsTitle As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litCCFee control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCCFee As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''Button1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
