'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace B2P.PaymentLanding.Express.Web
    
    Partial Public Class _paydefault
        
        '''<summary>
        '''docHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents docHead As Global.System.Web.UI.HtmlControls.HtmlHead
        
        '''<summary>
        '''lnkCSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkCSS As Global.System.Web.UI.HtmlControls.HtmlLink
        
        '''<summary>
        '''frmDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmDefault As Global.System.Web.UI.HtmlControls.HtmlForm
        
        '''<summary>
        '''phDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phDefault As Global.B2P.PaymentLanding.Express.Web.Header
        
        '''<summary>
        '''litJavascriptHeading control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litJavascriptHeading As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''pnlJSMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlJSMessage As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''litJavascriptMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litJavascriptMessage As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''pnlProducts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlProducts As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''litSelectProdct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litSelectProdct As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''ddlCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCategories As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''hdAccount1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdAccount1 As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''hdAccount2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdAccount2 As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''hdAccount3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdAccount3 As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''pnlAccount1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAccount1 As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''lblAccountNumber1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAccountNumber1 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtLookupAccount1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLookupAccount1 As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''pnlAccount2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAccount2 As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''lblAccountNumber2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAccountNumber2 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtLookupAccount2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLookupAccount2 As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''pnlAccount3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAccount3 As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''lblAccountNumber3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAccountNumber3 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtLookupAccount3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLookupAccount3 As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnLookup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnLookup As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnSubmit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''lblClientMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblClientMessage As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''pfMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pfMenu As Global.B2P.PaymentLanding.Express.Web.MenuFooter
        
        '''<summary>
        '''pfDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pfDefault As Global.B2P.PaymentLanding.Express.Web.Footer
        
        '''<summary>
        '''pnlLookupResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlLookupResults As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''divLookupAlert control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divLookupAlert As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''lblLookupHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLookupHeader As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''grdLookup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdLookup As Global.System.Web.UI.WebControls.GridView
        
        '''<summary>
        '''btnClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnClear As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnLookupGo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnLookupGo As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnLookupOK control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnLookupOK As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''pnlLookupError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlLookupError As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''divLookupAlertError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divLookupAlertError As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''lblLookupHeaderError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLookupHeaderError As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''btnCloseLookupErrorDialog control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCloseLookupErrorDialog As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
