'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace B2P.PaymentLanding.Express.Web
    
    Partial Public Class PaymentFailure
        
        '''<summary>
        '''docHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents docHead As Global.System.Web.UI.HtmlControls.HtmlHead
        
        '''<summary>
        '''lnkCSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkCSS As Global.System.Web.UI.HtmlControls.HtmlLink
        
        '''<summary>
        '''frmDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmDefault As Global.System.Web.UI.HtmlControls.HtmlForm
        
        '''<summary>
        '''phDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phDefault As Global.B2P.PaymentLanding.Express.Web.Header
        
        '''<summary>
        '''pnlNonSSOBreadcrumb control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlNonSSOBreadcrumb As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''pnlSSOBreadcrumb control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSSOBreadcrumb As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''psmFailureMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents psmFailureMessage As Global.B2P.PaymentLanding.Express.Web.StatusMessage
        
        '''<summary>
        '''litIntro2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litIntro2 As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litBullet1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litBullet1 As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litBullet2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litBullet2 As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''lnkBtnColHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkBtnColHelp As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''litBullet3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litBullet3 As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litBankAccountIntro control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litBankAccountIntro As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''btnCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnTryAgain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnTryAgain As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''pfDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pfDefault As Global.B2P.PaymentLanding.Express.Web.Footer
        
        '''<summary>
        '''litCCVTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCCVTitle As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litCVVDesc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCVVDesc As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''btnCloseCreditModal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCloseCreditModal As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
