'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace B2P.PaymentLanding.Express.Web
    
    Partial Public Class PaymentComplete
        
        '''<summary>
        '''docHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents docHead As Global.System.Web.UI.HtmlControls.HtmlHead
        
        '''<summary>
        '''lnkCSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkCSS As Global.System.Web.UI.HtmlControls.HtmlLink
        
        '''<summary>
        '''frmDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmDefault As Global.System.Web.UI.HtmlControls.HtmlForm
        
        '''<summary>
        '''phDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phDefault As Global.B2P.PaymentLanding.Express.Web.Header
        
        '''<summary>
        '''pjsJavascript control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pjsJavascript As Global.JavaScriptCheck
        
        '''<summary>
        '''pnlNonSSOBreadcrumb control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlNonSSOBreadcrumb As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''BreadCrumbMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BreadCrumbMenu As Global.BreadCrumbMenu
        
        '''<summary>
        '''pnlSSOBreadcrumb control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSSOBreadcrumb As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''BreadCrumbMenuSSO control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BreadCrumbMenuSSO As Global.BreadCrumbMenu
        
        '''<summary>
        '''litClientName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litClientName As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litThankYou control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litThankYou As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''PostBackStatusMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PostBackStatusMessage As Global.B2P.PaymentLanding.Express.Web.StatusMessage
        
        '''<summary>
        '''pnlAccountDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAccountDetails As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''litConfirmText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litConfirmText As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litConfirmationNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litConfirmationNumber As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''pnlAccount1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAccount1 As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''litAccountNumber1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAccountNumber1 As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litAccountNumber1Data control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAccountNumber1Data As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''pnlAccount2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAccount2 As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''litAccountNumber2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAccountNumber2 As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litAccountNumber2Data control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAccountNumber2Data As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''pnlAccount3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAccount3 As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''litAccountNumber3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAccountNumber3 As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litAccountNumber3Data control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAccountNumber3Data As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litPaymentDateText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPaymentDateText As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litPaymentDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPaymentDate As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litPaymentMethodText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPaymentMethodText As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litPaymentMethod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPaymentMethod As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''pnlEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlEmailAddress As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''litEmailAddressText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litEmailAddressText As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litEmailAddress As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litAmountText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAmountText As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAmount As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''pnlFees control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlFees As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''litFeeText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litFeeText As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litFee control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litFee As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litTotalAmountText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTotalAmountText As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litTotalAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTotalAmount As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litSystemMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litSystemMessage As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''pnlCreateProfile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCreateProfile As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''litCreateProfile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCreateProfile As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''Panel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''litClientMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litClientMessage As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''pfDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pfDefault As Global.B2P.PaymentLanding.Express.Web.Footer
        
        '''<summary>
        '''litFeesTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litFeesTitle As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litCreateProfileInstructions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCreateProfileInstructions As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''psmErrorMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents psmErrorMessage As Global.B2P.PaymentLanding.Express.Web.StatusMessage
        
        '''<summary>
        '''pnlCreateProfileForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCreateProfileForm As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''litUserID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litUserID As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''txtUserID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUserID As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''litPassword1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPassword1 As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litPasswordRequirements control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPasswordRequirements As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''Literal1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Literal1 As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litPasswordBullet1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPasswordBullet1 As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litPasswordBullet2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPasswordBullet2 As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litPasswordBullet3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPasswordBullet3 As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litPasswordBullet4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPasswordBullet4 As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''txtPassword1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPassword1 As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''litPassword2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPassword2 As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''txtPassword2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPassword2 As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''litProfileEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litProfileEmailAddress As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''txtProfileEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProfileEmailAddress As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''pnlCreditCardSuppInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCreditCardSuppInfo As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''litCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCountry As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''ddlCreditCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCreditCountry As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''litBillingZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litBillingZip As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''txtBillingZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBillingZip As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnCancelCreateProfile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancelCreateProfile As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnCreateProfile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCreateProfile As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
