'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace B2P.PaymentLanding.Express.Web

    Partial Public Class _Error

        '''<summary>
        '''docHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents docHead As Global.System.Web.UI.HtmlControls.HtmlHead

        '''<summary>
        '''frmError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmError As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''phError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phError As Global.B2P.PaymentLanding.Express.Web.Header

        '''<summary>
        '''psmError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents psmError As Global.B2P.PaymentLanding.Express.Web.StatusMessage

        '''<summary>
        '''pfError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pfError As Global.B2P.PaymentLanding.Express.Web.Footer
    End Class
End Namespace
