'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class WebResources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.WebResources", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to For payments made from commercial bank accounts, please confirm with your bank that electronic payment debits are allowed from company ID:.
        '''</summary>
        Friend Shared ReadOnly Property BankAccountCommercialMsg() As String
            Get
                Return ResourceManager.GetString("BankAccountCommercialMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I Agree.
        '''</summary>
        Friend Shared ReadOnly Property ButtonAgree() As String
            Get
                Return ResourceManager.GetString("ButtonAgree", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property ButtonCancel() As String
            Get
                Return ResourceManager.GetString("ButtonCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Friend Shared ReadOnly Property ButtonClose() As String
            Get
                Return ResourceManager.GetString("ButtonClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Continue.
        '''</summary>
        Friend Shared ReadOnly Property ButtonContinue() As String
            Get
                Return ResourceManager.GetString("ButtonContinue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pay Now.
        '''</summary>
        Friend Shared ReadOnly Property ButtonPayNow() As String
            Get
                Return ResourceManager.GetString("ButtonPayNow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print.
        '''</summary>
        Friend Shared ReadOnly Property ButtonPrint() As String
            Get
                Return ResourceManager.GetString("ButtonPrint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Submit.
        '''</summary>
        Friend Shared ReadOnly Property ButtonSubmit() As String
            Get
                Return ResourceManager.GetString("ButtonSubmit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Try Again.
        '''</summary>
        Friend Shared ReadOnly Property ButtonTryAgain() As String
            Get
                Return ResourceManager.GetString("ButtonTryAgain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The routing and account numbers can be located by looking on your check, as illustrated below:.
        '''</summary>
        Friend Shared ReadOnly Property CheckHelpModalDescription() As String
            Get
                Return ResourceManager.GetString("CheckHelpModalDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check Image.
        '''</summary>
        Friend Shared ReadOnly Property CheckHelpModalTitle() As String
            Get
                Return ResourceManager.GetString("CheckHelpModalTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I agree to the Terms and Conditions.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmAgreementTerms() As String
            Get
                Return ResourceManager.GetString("ConfirmAgreementTerms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to For a confirmation email, please enter your email address:.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmEmailInfo() As String
            Get
                Return ResourceManager.GetString("ConfirmEmailInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please review the details of your payment below before clicking &lt;span class=&quot;text-primary bold&quot;&gt;Pay Now&lt;/span&gt; to complete..
        '''</summary>
        Friend Shared ReadOnly Property ConfirmPaymentReviewDetails() As String
            Get
                Return ResourceManager.GetString("ConfirmPaymentReviewDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm Your Payment.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmPaymentTitle() As String
            Get
                Return ResourceManager.GetString("ConfirmPaymentTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Terms and Conditions.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmTermsConditions() As String
            Get
                Return ResourceManager.GetString("ConfirmTermsConditions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The CVV Number (Card Verification Value) is a 3 digit code on VISA, MasterCard and Discover branded credit and debit cards or a 4 digit code on American Express branded credit cards. &lt;br /&gt;&lt;br /&gt;They can be located by looking on your card, as illustrated below:.
        '''</summary>
        Friend Shared ReadOnly Property CVVModalDescription() As String
            Get
                Return ResourceManager.GetString("CVVModalDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to here.
        '''</summary>
        Friend Shared ReadOnly Property CVVModalLinkText() As String
            Get
                Return ResourceManager.GetString("CVVModalLinkText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Credit Card Security Codes.
        '''</summary>
        Friend Shared ReadOnly Property CVVModalTitle() As String
            Get
                Return ResourceManager.GetString("CVVModalTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid account number..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgAccountNumber() As String
            Get
                Return ResourceManager.GetString("ErrMsgAccountNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Must agree to the terms and conditions..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgAgreeToTerms() As String
            Get
                Return ResourceManager.GetString("ErrMsgAgreeToTerms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Accounts must contain 1-17 digits and match..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgBankAccount() As String
            Get
                Return ResourceManager.GetString("ErrMsgBankAccount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not a valid security code..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgCreditCardCVC() As String
            Get
                Return ResourceManager.GetString("ErrMsgCreditCardCVC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid expiration date..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgCreditCardExpiry() As String
            Get
                Return ResourceManager.GetString("ErrMsgCreditCardExpiry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not a valid credit card number..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgCreditCardNumber() As String
            Get
                Return ResourceManager.GetString("ErrMsgCreditCardNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Credit card type not accepted..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgCreditCardType() As String
            Get
                Return ResourceManager.GetString("ErrMsgCreditCardType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid date..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgDate() As String
            Get
                Return ResourceManager.GetString("ErrMsgDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid email address..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgEmailAddress() As String
            Get
                Return ResourceManager.GetString("ErrMsgEmailAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First name is empty or invalid..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgFirstName() As String
            Get
                Return ResourceManager.GetString("ErrMsgFirstName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please review the following errors and resubmit the form:.
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgHeader() As String
            Get
                Return ResourceManager.GetString("ErrMsgHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last name is empty or invalid..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgLastName() As String
            Get
                Return ResourceManager.GetString("ErrMsgLastName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid or missing card information..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgMissingCardInfo() As String
            Get
                Return ResourceManager.GetString("ErrMsgMissingCardInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NACHA form must be on file..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgNACHA() As String
            Get
                Return ResourceManager.GetString("ErrMsgNACHA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name on card is empty or invalid..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgNameOnCard() As String
            Get
                Return ResourceManager.GetString("ErrMsgNameOnCard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid amount..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgPaymentAmount() As String
            Get
                Return ResourceManager.GetString("ErrMsgPaymentAmount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Required..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgRequired() As String
            Get
                Return ResourceManager.GetString("ErrMsgRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missing or invalid routing number..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgRoutingNumber() As String
            Get
                Return ResourceManager.GetString("ErrMsgRoutingNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid or missing state/province..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgStateProvince() As String
            Get
                Return ResourceManager.GetString("ErrMsgStateProvince", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid zip code..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgZipCode() As String
            Get
                Return ResourceManager.GetString("ErrMsgZipCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If you were paying with a credit/debit card and did not receive a payment confirmation number, then your card may have been declined for any of the following conditions:.
        '''</summary>
        Friend Shared ReadOnly Property FailPageCreditExplanation() As String
            Get
                Return ResourceManager.GetString("FailPageCreditExplanation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;span class=&quot;bold&quot;&gt;Credit Card Information:&lt;/span&gt; Verify the card number and expiration dates are correct..
        '''</summary>
        Friend Shared ReadOnly Property FailPageCreditReason1() As String
            Get
                Return ResourceManager.GetString("FailPageCreditReason1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;span class=&quot;bold&quot;&gt;CVV:&lt;/span&gt; Verify that the CVV code is correct. For help identifying your CVV code, click.
        '''</summary>
        Friend Shared ReadOnly Property FailPageCreditReason2() As String
            Get
                Return ResourceManager.GetString("FailPageCreditReason2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;span class=&quot;bold&quot;&gt;General Card Decline:&lt;/span&gt; Your credit card company may have declined the payment attempt. Contact customer service or your credit card company for more information, or click on the link to the right to retry..
        '''</summary>
        Friend Shared ReadOnly Property FailPageCreditReason3() As String
            Get
                Return ResourceManager.GetString("FailPageCreditReason3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;span class=&quot;bold&quot;&gt;Your payment was not successful.&lt;/span&gt;.
        '''</summary>
        Friend Shared ReadOnly Property FailPageIntro() As String
            Get
                Return ResourceManager.GetString("FailPageIntro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Payment Failed.
        '''</summary>
        Friend Shared ReadOnly Property FailPageTitle() As String
            Get
                Return ResourceManager.GetString("FailPageTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thank You.
        '''</summary>
        Friend Shared ReadOnly Property SalutationDeclined() As String
            Get
                Return ResourceManager.GetString("SalutationDeclined", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your payment was successful. Your confirmation is: &lt;span class=&quot;bold&quot;&gt;#&lt;/span&gt;.
        '''</summary>
        Friend Shared ReadOnly Property SuccessConfirmationMsg() As String
            Get
                Return ResourceManager.GetString("SuccessConfirmationMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Payment Successful.
        '''</summary>
        Friend Shared ReadOnly Property SuccessPageTitle() As String
            Get
                Return ResourceManager.GetString("SuccessPageTitle", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
