'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddBlock

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ToolkitScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolkitScriptManager1 As Global.AjaxControlToolkit.ToolkitScriptManager

    '''<summary>
    '''menu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu As Global.Bill2PayAdmin45.menu

    '''<summary>
    '''logout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents logout As Global.Bill2PayAdmin45.logout1

    '''<summary>
    '''BlockPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BlockPanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlClient As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddlAUClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAUClient As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''pnlProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProduct As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlMessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMessages As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlHeaders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlHeaders As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddlProductList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProductList As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''reqProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqProducts As Global.PeterBlum.DES.Web.WebControls.RequiredTextValidator

    '''<summary>
    '''pnlAccount1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAccount1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblAccountNumber1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccountNumber1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''regAccountNumber1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regAccountNumber1 As Global.PeterBlum.DES.Web.WebControls.RegexValidator

    '''<summary>
    '''reqAccountNumber1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqAccountNumber1 As Global.PeterBlum.DES.Web.WebControls.RequiredTextValidator

    '''<summary>
    '''txtAccountNumber1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountNumber1 As Global.PeterBlum.DES.Web.WebControls.TextBox

    '''<summary>
    '''txtAccountNumber1_FilteredTextBoxExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountNumber1_FilteredTextBoxExtender As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''pnlAccount2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAccount2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblAccountNumber2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccountNumber2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''regAccountNumber2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regAccountNumber2 As Global.PeterBlum.DES.Web.WebControls.RegexValidator

    '''<summary>
    '''reqAccountNumber2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqAccountNumber2 As Global.PeterBlum.DES.Web.WebControls.RequiredTextValidator

    '''<summary>
    '''txtAccountNumber2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountNumber2 As Global.PeterBlum.DES.Web.WebControls.TextBox

    '''<summary>
    '''txtAccountNumber2_FilteredTextBoxExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountNumber2_FilteredTextBoxExtender As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''pnlAccount3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAccount3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblAccountNumber3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccountNumber3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''regAccountNumber3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regAccountNumber3 As Global.PeterBlum.DES.Web.WebControls.RegexValidator

    '''<summary>
    '''reqAccountNumber3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqAccountNumber3 As Global.PeterBlum.DES.Web.WebControls.RequiredTextValidator

    '''<summary>
    '''txtAccountNumber3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountNumber3 As Global.PeterBlum.DES.Web.WebControls.TextBox

    '''<summary>
    '''txtAccountNumber3_FilteredTextBoxExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountNumber3_FilteredTextBoxExtender As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''pnlLookupButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLookupButton As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnLookup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLookup As Global.PeterBlum.DES.Web.WebControls.ImageButton

    '''<summary>
    '''pnlButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlButton As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.PeterBlum.DES.Web.WebControls.ImageButton

    '''<summary>
    '''pnlClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlClear As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClear As Global.PeterBlum.DES.Web.WebControls.ImageButton

    '''<summary>
    '''pnlReEnterAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlReEnterAccount As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlAccount1r control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAccount1r As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblAccountNumber1r control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccountNumber1r As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAccountNumber1r control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountNumber1r As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''regAccountNumber1r control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regAccountNumber1r As Global.PeterBlum.DES.Web.WebControls.RegexValidator

    '''<summary>
    '''reqAccountNumber1r control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqAccountNumber1r As Global.PeterBlum.DES.Web.WebControls.RequiredTextValidator

    '''<summary>
    '''CompareTwoFieldsValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompareTwoFieldsValidator1 As Global.PeterBlum.DES.Web.WebControls.CompareTwoFieldsValidator

    '''<summary>
    '''txtAccountNumber1r_FilteredTextBoxExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountNumber1r_FilteredTextBoxExtender As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''pnlAccount2r control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAccount2r As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblAccountNumber2r control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccountNumber2r As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''regAccountNumber2r control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regAccountNumber2r As Global.PeterBlum.DES.Web.WebControls.RegexValidator

    '''<summary>
    '''reqAccountNumber2r control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqAccountNumber2r As Global.PeterBlum.DES.Web.WebControls.RequiredTextValidator

    '''<summary>
    '''txtAccountNumber2r control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountNumber2r As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAccountNumber2r_FilteredTextBoxExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountNumber2r_FilteredTextBoxExtender As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''CompareTwoFieldsValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompareTwoFieldsValidator2 As Global.PeterBlum.DES.Web.WebControls.CompareTwoFieldsValidator

    '''<summary>
    '''pnlAccount3r control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAccount3r As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblAccountNumber3r control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccountNumber3r As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''regAccountNumber3r control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regAccountNumber3r As Global.PeterBlum.DES.Web.WebControls.RegexValidator

    '''<summary>
    '''reqAccountNumber3r control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqAccountNumber3r As Global.PeterBlum.DES.Web.WebControls.RequiredTextValidator

    '''<summary>
    '''txtAccountNumber3r control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountNumber3r As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAccountNumber3r_FilteredTextBoxExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountNumber3r_FilteredTextBoxExtender As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''CompareTwoFieldsValidator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompareTwoFieldsValidator3 As Global.PeterBlum.DES.Web.WebControls.CompareTwoFieldsValidator

    '''<summary>
    '''pnlBlockDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBlockDetail As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''CountTrueConditionsValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CountTrueConditionsValidator1 As Global.PeterBlum.DES.Web.WebControls.CountTrueConditionsValidator

    '''<summary>
    '''pnlMessageDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMessageDetail As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMessageDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessageDetail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProduct As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlAccount1d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAccount1d As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblAccountNumber1d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccountNumber1d As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAccountNumber1d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountNumber1d As Global.PeterBlum.DES.Web.WebControls.TextBox

    '''<summary>
    '''pnlAccount2d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAccount2d As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblAccountNumber2d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccountNumber2d As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAccountNumber2d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountNumber2d As Global.PeterBlum.DES.Web.WebControls.TextBox

    '''<summary>
    '''pnlAccount3d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAccount3d As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblAccountNumber3d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccountNumber3d As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAccountNumber3d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountNumber3d As Global.PeterBlum.DES.Web.WebControls.TextBox

    '''<summary>
    '''pnlProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProfile As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblAutoPay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAutoPay As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkBtnProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBtnProfile As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDetail As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFirstName As Global.PeterBlum.DES.Web.WebControls.TextBox

    '''<summary>
    '''txtFirstName_FilteredTextBoxExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFirstName_FilteredTextBoxExtender As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''txtLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastName As Global.PeterBlum.DES.Web.WebControls.TextBox

    '''<summary>
    '''txtLastName_FilteredTextBoxExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastName_FilteredTextBoxExtender As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''cbEcheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbEcheck As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbCreditCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbCreditCard As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailAddress As Global.PeterBlum.DES.Web.WebControls.TextBox

    '''<summary>
    '''txtEmailAddress_FilteredTextBoxExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailAddress_FilteredTextBoxExtender As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''regEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''RequiredTextValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredTextValidator1 As Global.PeterBlum.DES.Web.WebControls.RequiredTextValidator

    '''<summary>
    '''cbSendEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSendEmail As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComments As Global.PeterBlum.DES.Web.WebControls.TextBox

    '''<summary>
    '''FilteredTextBoxExtender2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredTextBoxExtender2 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.PeterBlum.DES.Web.WebControls.ImageButton

    '''<summary>
    '''btnSubmitBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitBlock As Global.PeterBlum.DES.Web.WebControls.ImageButton

    '''<summary>
    '''Footer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Footer As Global.Bill2PayAdmin45.footer
End Class
