// <auto-generated />
namespace Bill2Pay.Model.DataContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class p31 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(p31));
        
        string IMigrationMetadata.Id
        {
            get { return "201702241005450_p31"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
