// <auto-generated />
namespace Bill2Pay.Model.DataContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class P1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(P1));
        
        string IMigrationMetadata.Id
        {
            get { return "201702230921494_P1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
