//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bill2Pay.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class ImportSummary
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int Id { get; set; }

        public int PaymentYear { get; set; }

        public DateTime ImportDate { get; set; }

        [MaxLength(100)]
        public string FileName { get; set; }

        public Nullable<int> RecordCount { get; set; }

        [MaxLength(1024)]
        public String ProcessLog { get; set; }

        public virtual ICollection<ImportDetail> ImportDetails { get; set; }

        public bool IsActive { get; set; }
        public DateTime DateAdded { get; set; }

        [ForeignKey("CreatedUser")]
        public long UserId { get; set; }

        public virtual ApplicationUser CreatedUser { get; set; }
    }
}
