//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bill2Pay.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class SubmissionDetail : IRSDetail
    {
        [Key, Column(Order = 0)]
        public string AccountNo { get; set; }

        [Key, Column(Order = 1)]
        [ForeignKey("SubmissionSummary")]
        public int SubmissionId { get; set; }

        public virtual SubmissionSummary SubmissionSummary { get; set; }
    }
}
