'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class confirmation
    
    '''<summary>
    '''docHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents docHead As Global.System.Web.UI.HtmlControls.HtmlHead
    
    '''<summary>
    '''frmConfirmation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmConfirmation As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''imgClientLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgClientLogo As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''litMerchantHeaderInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMerchantHeaderInfo As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litCardAndPaymentType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCardAndPaymentType As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlEmvAppId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEmvAppId As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''litEmvAppId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEmvAppId As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litMechantLocationCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMechantLocationCode As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litCardHolderName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCardHolderName As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litReferenceNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litReferenceNumber As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litAccountNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAccountNumber As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litCardType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCardType As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litEntryMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEntryMode As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAmount As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litConvenienceFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litConvenienceFee As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litPayType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPayType As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litTotalAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTotalAmount As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litTransStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTransStatus As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlApprovalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlApprovalCode As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''litApprovalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litApprovalCode As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlHostCodes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlHostCodes As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''litHostCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litHostCode As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litTransID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTransID As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlEmvCrypto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEmvCrypto As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''litEmvCrypto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEmvCrypto As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlSignatureInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSignatureInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''litSignatureNotNeeded control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSignatureNotNeeded As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''imgSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSignature As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''pnlEmvTags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEmvTags As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''litEmvTags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEmvTags As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litSalutation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSalutation As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''hidEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidEmailAddress As Global.System.Web.UI.WebControls.HiddenField
End Class
