'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class WebResources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.WebResources", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account Details.
        '''</summary>
        Friend Shared ReadOnly Property AccountDetails() As String
            Get
                Return ResourceManager.GetString("AccountDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid bank account number.
        '''</summary>
        Friend Shared ReadOnly Property ACHInvalidModalTitle() As String
            Get
                Return ResourceManager.GetString("ACHInvalidModalTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add More Items.
        '''</summary>
        Friend Shared ReadOnly Property AddMoreItemsButton() As String
            Get
                Return ResourceManager.GetString("AddMoreItemsButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address1.
        '''</summary>
        Friend Shared ReadOnly Property Address1Label() As String
            Get
                Return ResourceManager.GetString("Address1Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address2.
        '''</summary>
        Friend Shared ReadOnly Property Address2Label() As String
            Get
                Return ResourceManager.GetString("Address2Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add To Cart.
        '''</summary>
        Friend Shared ReadOnly Property AddToCartButton() As String
            Get
                Return ResourceManager.GetString("AddToCartButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Amount.
        '''</summary>
        Friend Shared ReadOnly Property AmountLabel() As String
            Get
                Return ResourceManager.GetString("AmountLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to For payments made from commercial bank accounts, please confirm with your bank that electronic payment debits are allowed from company ID:.
        '''</summary>
        Friend Shared ReadOnly Property BankAccountCommercialMsg() As String
            Get
                Return ResourceManager.GetString("BankAccountCommercialMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create Profile.
        '''</summary>
        Friend Shared ReadOnly Property btnCreateProfile() As String
            Get
                Return ResourceManager.GetString("btnCreateProfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print for your Records.
        '''</summary>
        Friend Shared ReadOnly Property btnPrint() As String
            Get
                Return ResourceManager.GetString("btnPrint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Continue.
        '''</summary>
        Friend Shared ReadOnly Property ButtonAddToCartContinue() As String
            Get
                Return ResourceManager.GetString("ButtonAddToCartContinue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I Agree.
        '''</summary>
        Friend Shared ReadOnly Property ButtonAgree() As String
            Get
                Return ResourceManager.GetString("ButtonAgree", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property ButtonCancel() As String
            Get
                Return ResourceManager.GetString("ButtonCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear.
        '''</summary>
        Friend Shared ReadOnly Property ButtonClear() As String
            Get
                Return ResourceManager.GetString("ButtonClear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Friend Shared ReadOnly Property ButtonClose() As String
            Get
                Return ResourceManager.GetString("ButtonClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Continue.
        '''</summary>
        Friend Shared ReadOnly Property ButtonContinue() As String
            Get
                Return ResourceManager.GetString("ButtonContinue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Convenience fees may apply.
        '''</summary>
        Friend Shared ReadOnly Property ButtonConvFee() As String
            Get
                Return ResourceManager.GetString("ButtonConvFee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create Profile.
        '''</summary>
        Friend Shared ReadOnly Property ButtonCreateProfile() As String
            Get
                Return ResourceManager.GetString("ButtonCreateProfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm and Continue.
        '''</summary>
        Friend Shared ReadOnly Property ButtonLookupGo() As String
            Get
                Return ResourceManager.GetString("ButtonLookupGo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Make a Payment.
        '''</summary>
        Friend Shared ReadOnly Property ButtonMakeAPayment() As String
            Get
                Return ResourceManager.GetString("ButtonMakeAPayment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pay Now.
        '''</summary>
        Friend Shared ReadOnly Property ButtonPayNow() As String
            Get
                Return ResourceManager.GetString("ButtonPayNow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print.
        '''</summary>
        Friend Shared ReadOnly Property ButtonPrint() As String
            Get
                Return ResourceManager.GetString("ButtonPrint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Submit.
        '''</summary>
        Friend Shared ReadOnly Property ButtonSubmit() As String
            Get
                Return ResourceManager.GetString("ButtonSubmit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Try Again.
        '''</summary>
        Friend Shared ReadOnly Property ButtonTryAgain() As String
            Get
                Return ResourceManager.GetString("ButtonTryAgain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The routing and account numbers can be located by looking on your check, as illustrated below:.
        '''</summary>
        Friend Shared ReadOnly Property CheckHelpModalDescription() As String
            Get
                Return ResourceManager.GetString("CheckHelpModalDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check Image.
        '''</summary>
        Friend Shared ReadOnly Property CheckHelpModalTitle() As String
            Get
                Return ResourceManager.GetString("CheckHelpModalTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to City.
        '''</summary>
        Friend Shared ReadOnly Property CityLabel() As String
            Get
                Return ResourceManager.GetString("CityLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This Combination of item and account numbers already exists in the cart! Please use a different combination..
        '''</summary>
        Friend Shared ReadOnly Property CombineValidationAddToCart() As String
            Get
                Return ResourceManager.GetString("CombineValidationAddToCart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I agree to the Terms and Conditions.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmAgreementTerms() As String
            Get
                Return ResourceManager.GetString("ConfirmAgreementTerms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirmation Email.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmEmailInfo() As String
            Get
                Return ResourceManager.GetString("ConfirmEmailInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Convenience Fee.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmFeeConditions() As String
            Get
                Return ResourceManager.GetString("ConfirmFeeConditions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I accept the convenience fee.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmFeeTerms() As String
            Get
                Return ResourceManager.GetString("ConfirmFeeTerms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please review the details of your payment below before clicking &lt;span class=&quot;text-primary bold&quot;&gt;Pay Now&lt;/span&gt; to complete..
        '''</summary>
        Friend Shared ReadOnly Property ConfirmPaymentReviewDetails() As String
            Get
                Return ResourceManager.GetString("ConfirmPaymentReviewDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm Your Payment.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmPaymentTitle() As String
            Get
                Return ResourceManager.GetString("ConfirmPaymentTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Terms and Conditions.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmTermsConditions() As String
            Get
                Return ResourceManager.GetString("ConfirmTermsConditions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Information.
        '''</summary>
        Friend Shared ReadOnly Property ContactInfo() As String
            Get
                Return ResourceManager.GetString("ContactInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter Contact Information.
        '''</summary>
        Friend Shared ReadOnly Property ContactInfoTitle() As String
            Get
                Return ResourceManager.GetString("ContactInfoTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Name.
        '''</summary>
        Friend Shared ReadOnly Property ContactName() As String
            Get
                Return ResourceManager.GetString("ContactName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create Profile.
        '''</summary>
        Friend Shared ReadOnly Property CreateProfileTitle() As String
            Get
                Return ResourceManager.GetString("CreateProfileTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The CVV Number (Card Verification Value) is a 3 digit code on VISA, MasterCard and Discover branded credit and debit cards or a 4 digit code on American Express branded credit cards. &lt;br /&gt;&lt;br /&gt;They can be located by looking on your card, as illustrated below:.
        '''</summary>
        Friend Shared ReadOnly Property CVVModalDescription() As String
            Get
                Return ResourceManager.GetString("CVVModalDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to here.
        '''</summary>
        Friend Shared ReadOnly Property CVVModalLinkText() As String
            Get
                Return ResourceManager.GetString("CVVModalLinkText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Credit Card Security Codes.
        '''</summary>
        Friend Shared ReadOnly Property CVVModalTitle() As String
            Get
                Return ResourceManager.GetString("CVVModalTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid account number..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgAccountNumber() As String
            Get
                Return ResourceManager.GetString("ErrMsgAccountNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Must agree to the convenience fee.
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgAgreeToFees() As String
            Get
                Return ResourceManager.GetString("ErrMsgAgreeToFees", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Must agree to the terms and conditions..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgAgreeToTerms() As String
            Get
                Return ResourceManager.GetString("ErrMsgAgreeToTerms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid amount.
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgAmount() As String
            Get
                Return ResourceManager.GetString("ErrMsgAmount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Accounts must contain 1-17 digits and match..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgBankAccount() As String
            Get
                Return ResourceManager.GetString("ErrMsgBankAccount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not a valid security code..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgCreditCardCVC() As String
            Get
                Return ResourceManager.GetString("ErrMsgCreditCardCVC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid expiration date..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgCreditCardExpiry() As String
            Get
                Return ResourceManager.GetString("ErrMsgCreditCardExpiry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not a valid credit card number or card type not accepted..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgCreditCardNumber() As String
            Get
                Return ResourceManager.GetString("ErrMsgCreditCardNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Credit card type not accepted..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgCreditCardType() As String
            Get
                Return ResourceManager.GetString("ErrMsgCreditCardType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid date..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgDate() As String
            Get
                Return ResourceManager.GetString("ErrMsgDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid email address..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgEmailAddress() As String
            Get
                Return ResourceManager.GetString("ErrMsgEmailAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First name is empty or invalid..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgFirstName() As String
            Get
                Return ResourceManager.GetString("ErrMsgFirstName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please review the following errors and resubmit the form:.
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgHeader() As String
            Get
                Return ResourceManager.GetString("ErrMsgHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last name is empty or invalid..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgLastName() As String
            Get
                Return ResourceManager.GetString("ErrMsgLastName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missing or invalid client.
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgMissingClient() As String
            Get
                Return ResourceManager.GetString("ErrMsgMissingClient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name on bank account is empty or invalid..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgNameOnBankAccount() As String
            Get
                Return ResourceManager.GetString("ErrMsgNameOnBankAccount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name on card is empty or invalid..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgNameOnCard() As String
            Get
                Return ResourceManager.GetString("ErrMsgNameOnCard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid amount..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgPaymentAmount() As String
            Get
                Return ResourceManager.GetString("ErrMsgPaymentAmount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Required..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgRequired() As String
            Get
                Return ResourceManager.GetString("ErrMsgRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missing or invalid routing number..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgRoutingNumber() As String
            Get
                Return ResourceManager.GetString("ErrMsgRoutingNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid or missing state/province..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgStateProvince() As String
            Get
                Return ResourceManager.GetString("ErrMsgStateProvince", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid zip code..
        '''</summary>
        Friend Shared ReadOnly Property ErrMsgZipCode() As String
            Get
                Return ResourceManager.GetString("ErrMsgZipCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password is invalid.
        '''</summary>
        Friend Shared ReadOnly Property ErrPassword() As String
            Get
                Return ResourceManager.GetString("ErrPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If you were paying with your bank account, there may have been an Internet connection or system issue.  Please retry using the link below, or contact customer service to confirm the status of your payment submission..
        '''</summary>
        Friend Shared ReadOnly Property FailPageBankAccountExplanation() As String
            Get
                Return ResourceManager.GetString("FailPageBankAccountExplanation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If you were paying with a credit/debit card and did not receive a payment confirmation number, then your card may have been declined for any of the following conditions:.
        '''</summary>
        Friend Shared ReadOnly Property FailPageCreditExplanation() As String
            Get
                Return ResourceManager.GetString("FailPageCreditExplanation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;span class=&quot;bold&quot;&gt;Credit Card Information:&lt;/span&gt; Verify the card number and expiration dates are correct..
        '''</summary>
        Friend Shared ReadOnly Property FailPageCreditReason1() As String
            Get
                Return ResourceManager.GetString("FailPageCreditReason1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;span class=&quot;bold&quot;&gt;CVV:&lt;/span&gt; Verify that the CVV code is correct. For help identifying your CVV code, click.
        '''</summary>
        Friend Shared ReadOnly Property FailPageCreditReason2() As String
            Get
                Return ResourceManager.GetString("FailPageCreditReason2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;span class=&quot;bold&quot;&gt;General Card Decline:&lt;/span&gt; Your credit card company may have declined the payment attempt. Contact customer service or your credit card company for more information, or click on the link to the right to retry..
        '''</summary>
        Friend Shared ReadOnly Property FailPageCreditReason3() As String
            Get
                Return ResourceManager.GetString("FailPageCreditReason3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;span class=&quot;bold&quot;&gt;Your payment was not successful.&lt;/span&gt;.
        '''</summary>
        Friend Shared ReadOnly Property FailPageIntro() As String
            Get
                Return ResourceManager.GetString("FailPageIntro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Payment Failed.
        '''</summary>
        Friend Shared ReadOnly Property FailPageTitle() As String
            Get
                Return ResourceManager.GetString("FailPageTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Convenience Fee Information.
        '''</summary>
        Friend Shared ReadOnly Property FeeInfoModalTitle() As String
            Get
                Return ResourceManager.GetString("FeeInfoModalTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Zip.
        '''</summary>
        Friend Shared ReadOnly Property InvalidZipMsg() As String
            Get
                Return ResourceManager.GetString("InvalidZipMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Javascript Disabled.
        '''</summary>
        Friend Shared ReadOnly Property JavascriptHeading() As String
            Get
                Return ResourceManager.GetString("JavascriptHeading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Javascript must be enabled in order for this site to work correctly..
        '''</summary>
        Friend Shared ReadOnly Property JavascriptMessage() As String
            Get
                Return ResourceManager.GetString("JavascriptMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Payment Amount.
        '''</summary>
        Friend Shared ReadOnly Property LblAmount() As String
            Get
                Return ResourceManager.GetString("LblAmount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Amount Due.
        '''</summary>
        Friend Shared ReadOnly Property LblAmountDue() As String
            Get
                Return ResourceManager.GetString("LblAmountDue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bank Account Payments.
        '''</summary>
        Friend Shared ReadOnly Property lblBankAccountPayments() As String
            Get
                Return ResourceManager.GetString("lblBankAccountPayments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bank Account.
        '''</summary>
        Friend Shared ReadOnly Property lblBankAccountTabName() As String
            Get
                Return ResourceManager.GetString("lblBankAccountTabName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Postal Code.
        '''</summary>
        Friend Shared ReadOnly Property lblBillingPostalCode() As String
            Get
                Return ResourceManager.GetString("lblBillingPostalCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Billing Zip.
        '''</summary>
        Friend Shared ReadOnly Property lblBillingZip() As String
            Get
                Return ResourceManager.GetString("lblBillingZip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirmation Number.
        '''</summary>
        Friend Shared ReadOnly Property LblConfirmationNumber() As String
            Get
                Return ResourceManager.GetString("LblConfirmationNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Country.
        '''</summary>
        Friend Shared ReadOnly Property lblCountry() As String
            Get
                Return ResourceManager.GetString("lblCountry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Want to make this process easier? Create a profile with the information used for this transaction..
        '''</summary>
        Friend Shared ReadOnly Property lblCreateProfile() As String
            Get
                Return ResourceManager.GetString("lblCreateProfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Credit Card Number.
        '''</summary>
        Friend Shared ReadOnly Property lblCreditCardNumber() As String
            Get
                Return ResourceManager.GetString("lblCreditCardNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Card Payments.
        '''</summary>
        Friend Shared ReadOnly Property lblCreditCardPayments() As String
            Get
                Return ResourceManager.GetString("lblCreditCardPayments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Credit Card.
        '''</summary>
        Friend Shared ReadOnly Property lblCreditCardTabName() As String
            Get
                Return ResourceManager.GetString("lblCreditCardTabName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Due Date.
        '''</summary>
        Friend Shared ReadOnly Property LblDueDate() As String
            Get
                Return ResourceManager.GetString("LblDueDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit Details.
        '''</summary>
        Friend Shared ReadOnly Property lblEditDetails() As String
            Get
                Return ResourceManager.GetString("lblEditDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email Address.
        '''</summary>
        Friend Shared ReadOnly Property lblEmailAddress() As String
            Get
                Return ResourceManager.GetString("lblEmailAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirmation Email.
        '''</summary>
        Friend Shared ReadOnly Property LblEmailAddressText() As String
            Get
                Return ResourceManager.GetString("LblEmailAddressText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Expiration Date.
        '''</summary>
        Friend Shared ReadOnly Property lblExpirationDate() As String
            Get
                Return ResourceManager.GetString("lblExpirationDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Convenience Fee.
        '''</summary>
        Friend Shared ReadOnly Property LblFee() As String
            Get
                Return ResourceManager.GetString("LblFee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Important Message.
        '''</summary>
        Friend Shared ReadOnly Property lblImportantMessage() As String
            Get
                Return ResourceManager.GetString("lblImportantMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name on Account.
        '''</summary>
        Friend Shared ReadOnly Property LblNameOnAccount() As String
            Get
                Return ResourceManager.GetString("LblNameOnAccount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name on Card.
        '''</summary>
        Friend Shared ReadOnly Property lblNameonCard() As String
            Get
                Return ResourceManager.GetString("lblNameonCard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend Shared ReadOnly Property lblPassword1() As String
            Get
                Return ResourceManager.GetString("lblPassword1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Re-type Password.
        '''</summary>
        Friend Shared ReadOnly Property lblPassword2() As String
            Get
                Return ResourceManager.GetString("lblPassword2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click here for password requirements.
        '''</summary>
        Friend Shared ReadOnly Property lblPasswordRequirements() As String
            Get
                Return ResourceManager.GetString("lblPasswordRequirements", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Passwords must be at least 8 characters and contain 3 of the 4 conditions:.
        '''</summary>
        Friend Shared ReadOnly Property lblPasswordRequirementsIntro() As String
            Get
                Return ResourceManager.GetString("lblPasswordRequirementsIntro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Payment Amount Information.
        '''</summary>
        Friend Shared ReadOnly Property lblPaymentAmountTitle() As String
            Get
                Return ResourceManager.GetString("lblPaymentAmountTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Payment Date.
        '''</summary>
        Friend Shared ReadOnly Property LblPaymentDate() As String
            Get
                Return ResourceManager.GetString("LblPaymentDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Payment Method.
        '''</summary>
        Friend Shared ReadOnly Property LblPaymentMethod() As String
            Get
                Return ResourceManager.GetString("LblPaymentMethod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Review your payment details.
        '''</summary>
        Friend Shared ReadOnly Property lblReviewPayment() As String
            Get
                Return ResourceManager.GetString("lblReviewPayment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Payment Amount.
        '''</summary>
        Friend Shared ReadOnly Property lblSelectAmount() As String
            Get
                Return ResourceManager.GetString("lblSelectAmount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Payment Method.
        '''</summary>
        Friend Shared ReadOnly Property lblSelectPaymentMethod() As String
            Get
                Return ResourceManager.GetString("lblSelectPaymentMethod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Product/Service.
        '''</summary>
        Friend Shared ReadOnly Property lblSelectProductService() As String
            Get
                Return ResourceManager.GetString("lblSelectProductService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address.
        '''</summary>
        Friend Shared ReadOnly Property LblServiceAddressText() As String
            Get
                Return ResourceManager.GetString("LblServiceAddressText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total.
        '''</summary>
        Friend Shared ReadOnly Property LblTotalAmount() As String
            Get
                Return ResourceManager.GetString("LblTotalAmount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User Name.
        '''</summary>
        Friend Shared ReadOnly Property lblUserID() As String
            Get
                Return ResourceManager.GetString("lblUserID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missing or Invalid Client Information.
        '''</summary>
        Friend Shared ReadOnly Property MissingClientHeading() As String
            Get
                Return ResourceManager.GetString("MissingClientHeading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uppercase letter.
        '''</summary>
        Friend Shared ReadOnly Property PasswordRequirementBullet1() As String
            Get
                Return ResourceManager.GetString("PasswordRequirementBullet1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lowercase letter.
        '''</summary>
        Friend Shared ReadOnly Property PasswordRequirementBullet2() As String
            Get
                Return ResourceManager.GetString("PasswordRequirementBullet2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number.
        '''</summary>
        Friend Shared ReadOnly Property PasswordRequirementBullet3() As String
            Get
                Return ResourceManager.GetString("PasswordRequirementBullet3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Special character (excludes: &quot; &amp; ; &lt; &gt;).
        '''</summary>
        Friend Shared ReadOnly Property PasswordRequirementBullet4() As String
            Get
                Return ResourceManager.GetString("PasswordRequirementBullet4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm Payment .
        '''</summary>
        Friend Shared ReadOnly Property PaymentConfirm() As String
            Get
                Return ResourceManager.GetString("PaymentConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Payment Details.
        '''</summary>
        Friend Shared ReadOnly Property PaymentDetails() As String
            Get
                Return ResourceManager.GetString("PaymentDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Payment Failed.
        '''</summary>
        Friend Shared ReadOnly Property PaymentFailed() As String
            Get
                Return ResourceManager.GetString("PaymentFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Payment Success.
        '''</summary>
        Friend Shared ReadOnly Property PaymentSuccess() As String
            Get
                Return ResourceManager.GetString("PaymentSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phone.
        '''</summary>
        Friend Shared ReadOnly Property PhoneLabel() As String
            Get
                Return ResourceManager.GetString("PhoneLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Property Address.
        '''</summary>
        Friend Shared ReadOnly Property PropertyAddressTitle() As String
            Get
                Return ResourceManager.GetString("PropertyAddressTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selected Item.
        '''</summary>
        Friend Shared ReadOnly Property SelectedItemEdit() As String
            Get
                Return ResourceManager.GetString("SelectedItemEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to State.
        '''</summary>
        Friend Shared ReadOnly Property StateLabel() As String
            Get
                Return ResourceManager.GetString("StateLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your payment was successful. Your confirmation is: &lt;span class=&quot;bold&quot;&gt;#&lt;/span&gt;.
        '''</summary>
        Friend Shared ReadOnly Property SuccessConfirmationMsg() As String
            Get
                Return ResourceManager.GetString("SuccessConfirmationMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Payment Successful.
        '''</summary>
        Friend Shared ReadOnly Property SuccessPageTitle() As String
            Get
                Return ResourceManager.GetString("SuccessPageTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thank you for your payment!.
        '''</summary>
        Friend Shared ReadOnly Property ThankYouforYourPayment() As String
            Get
                Return ResourceManager.GetString("ThankYouforYourPayment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zip.
        '''</summary>
        Friend Shared ReadOnly Property ZipLabel() As String
            Get
                Return ResourceManager.GetString("ZipLabel", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
