//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bill2Pay.Model
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// Structure of Status
    /// </summary>
    public class Status
    {
        /// <summary>
        /// Database identity
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Status name
        /// </summary>
        [MaxLength(255)]
        public string Name { get; set; }

        /// <summary>
        /// Relation with Submission summary
        /// </summary>
        public virtual ICollection<SubmissionSummary> SubmissionProcess { get; set; }
    }
}
