//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bill2Pay.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class SubmissionDetail : IRSDetail
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int Id { get; set; }

        [MaxLength(20)]
        [Display(Name = "Account")]
        public string AccountNo { get; set; }

        [ForeignKey("SubmissionSummary")]
        public int SubmissionId { get; set; }

        [Display(Name = "Status")]
        public int SubmissionType { get; set; }

        public virtual SubmissionSummary SubmissionSummary { get; set; }

        [ForeignKey("PSE")]
        public virtual Nullable<int> PseId { get; set; }

        public PSEDetails PSE { get; set; }
    }
}
