'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace B2P.PaymentLanding.Express.Web
    
    Partial Public Class BankAccount
        
        '''<summary>
        '''txtNameonBankAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNameonBankAccount As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ddlBankAccountType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlBankAccountType As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''txtBankRoutingNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBankRoutingNumber As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtBankAccountNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBankAccountNumber As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
