'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CartDetails
    
    '''<summary>
    '''tblCartDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblCartDetails As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''tdDisplayCartMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdDisplayCartMsg As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''cartProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cartProduct As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cartHeadingCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cartHeadingCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cartHeadingAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cartHeadingAmount As Global.System.Web.UI.WebControls.Label
End Class
