'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CartDetails
    
    '''<summary>
    '''tblCartDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblCartDetails As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''tdDisplayCartMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdDisplayCartMsg As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''cartProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cartProduct As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCartHeadingText1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCartHeadingText1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCartText1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCartText1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCartHeadingCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCartHeadingCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCartText2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCartText2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCartHeadingAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCartHeadingAmount As Global.System.Web.UI.WebControls.Label
End Class
