'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace B2P.PaymentLanding.Express.Web
    
    Partial Public Class CreditCard
        
        '''<summary>
        '''litNameonCard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litNameonCard As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''txtNameonCard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNameonCard As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''litCreditCardNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCreditCardNumber As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litCardImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCardImages As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''txtCreditCardNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCreditCardNumber As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''litExpirationDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litExpirationDate As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''txtExpireDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExpireDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtCCV control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCCV As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''litCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCountry As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''ddlCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCountry As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''hdZipRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdZipRequired As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''litBillingZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litBillingZip As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''txtBillingZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBillingZip As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
