'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace B2P.PaymentLanding.Express.Web
    
    Partial Public Class EditPayment
        
        '''<summary>
        '''lnkEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkEdit As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''lblPaymentMethod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPaymentMethod As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''pnlExpDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlExpDate As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''lblExpDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExpDate As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''pnlZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlZip As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''lblBillingZipCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBillingZipCaption As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblBillZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBillZip As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
