'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace B2P.PaymentLanding.Express.Web

    Partial Public Class SessionExpired

        '''<summary>
        '''docHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents docHead As Global.System.Web.UI.HtmlControls.HtmlHead

        '''<summary>
        '''frmSessionExpired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmSessionExpired As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''phConfirmPaymentInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phConfirmPaymentInfo As Global.B2P.PaymentLanding.Express.Web.Header

        '''<summary>
        '''psmSessionExpired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents psmSessionExpired As Global.B2P.PaymentLanding.Express.Web.StatusMessage

        '''<summary>
        '''pfSessionExpired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pfSessionExpired As Global.B2P.PaymentLanding.Express.Web.Footer
    End Class
End Namespace
